export const FETCH_PEOPLES = 'FETCH/ASSIGNMENT/PEOPLES';
export const FETCH_PEOPLES_SUCCESS = `${FETCH_PEOPLES}/SUCCESS`;
export const FETCH_PEOPLES_ERROR = `${FETCH_PEOPLES}/ERROR`;
export const SET_USER_NAME = 'SET_USER_NAME';
export const LOGIN_STATE_KEY = 'user'
